backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Блог Постови"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Наслов", name: "title", widget: "string" }
      - { label: "Датум", name: "date", widget: "datetime" }
      - { label: "Автор", name: "author", widget: "string", default: "MHRA" }
      - { label: "Содржина", name: "body", widget: "markdown" }
